=== junaid-atari/crm-shopify-extensions/src/schemas/extension.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Shopify Extension Generator Schemas",
  "type": "object",
  "properties": {
    "handle": {
      "type": "string",
      "pattern": "^[a-z][a-z]+(-[a-z]+)+$",
      "minLength": 4,
      "maxLength": 60
    },
    "name": {
      "type": "string",
      "minLength": 4,
      "maxLength": 60
    },
    "description": {
      "type": "string",
      "minLength": 10,
      "maxLength": 100
    },
    "templatePath": {
      "type": "string",
      "minLength": 10
    },
    "targetPath": {
      "type": "string",
      "minLength": 10
    }
  },
  "required": [
    "handle",
    "name",
    "description",
    "templatePath",
    "targetPath"
  ]
}

=== junaid-atari/crm-shopify-extensions/src/extensions/send-professional-letter.ext.json
{
  "handle": "send-professional-letter",
  "name": "Send Professional Letter",
  "description": "Create and mail a professional letter using Open Letter Connect.",
  "templatePath": "{{srcPath}}/templates/shopify-extension.njk",
  "targetPath": "{{rootPath}}/extensions/{{handle}}/shopify.extension.toml"
}

=== junaid-atari/crm-shopify-extensions/src/extensions/send-real-penned-letter.ext.json
{
  "handle": "send-real-penned-letter",
  "name": "Send Real Penned Letter",
  "description": "Create and mail a real penned letter using Open Letter Connect.",
  "templatePath": "{{srcPath}}/templates/shopify-extension.njk",
  "targetPath": "{{rootPath}}/extensions/{{handle}}/shopify.extension.toml"
}
